### ISSUE TITLE
Import error when trying to use `kgtool --help`

### ISSUE THREAD

**Issue by DaoKevin** [process-intelligence-research/ChemEngKG_kgtool#154]
## 🐛 Bug Report

When I try to display the help page for the kgtool in the console, I get an import error.

## 🔬 How To Reproduce

Install kgtool via pip:
```
pip install git+https://github.com/process-intelligence-research/ChemEngKG_kgtool
```
then, run the help page
```
kgtool --help
```

### Code sample
```
kgtool --help
```

```python
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\PycharmProjects\Data_mining_services\venv\Scripts\kgtool.exe\__main__.py", line 4, in <module>
  File "C:\Users\User\PycharmProjects\Data_mining_services\venv\lib\site-packages\kgtool\__main__.py", line 11, in <module>
    from kgtool.interface import connect, fullGraph
ImportError: cannot import name 'fullGraph' from 'kgtool.interface' (C:\Users\User\PycharmProjects\Data_mining_services\venv\lib\site-packages\kgtool\interface.py)

```
### Environment

* OS: Windows 10
* Python version: 3.10.8

## 📈 Expected behavior

The help page should be displayed.

**Comment by kondakoffer** [comment]
Please reinstall the kgtool and try again now.
If this fixed it close the issue.
Note that the help page is currently very rudimentary.

**Comment by DaoKevin** [comment]
Resolved, thanks!
